### PR TITLE
Add error message if wrong args supplied

### PR DESCRIPTION
**Pull request by joezuntz**
I'd like to start thinking about things to use this from TXPipe to get covariances there.  If it's okay with you I might make a few PRs here.

Here's a first test one - it just adds an error message if you use the wrong arguments.

### CODE REVIEW

**Review by elikrause — COMMENTED** [review]
Compiles, makes sense, improves code.
Not sure if you're always considering 3x2pt - if not, adding the same in compute_covariances_real_WL_response.c might make sense too.

**Comment by joezuntz** [comment]
Good point - I've added that too.

**Comment by elikrause** [comment]
Not sure what you intend for the scope of this PR - should this include
checking that the ini file has all the required information? Or is that a
later PR?


Am Mi., 22. Juli 2020 um 19:02 Uhr schrieb joezuntz <
notifications@github.com>:

**Comment by joezuntz** [comment]
I'll do things piecemeal as I don't know how much time I'll have for different things.  So I think that's enough for now!

**Pull request merged**
